version: "3.3"
services:
  server:
    image: stremio/server:latest
    ports:
      - "11470:11470"
      - "12470:12470"
    volumes:
      - stremio_data:/root/.stremio-server
    environment:
      - FFMPEG_BIN=/usr/bin/ffmpeg
      - FFPROBE_BIN=/usr/bin/ffprobe
      - APP_PATH=/root/.stremio-server
      - NO_CORS=1

volumes:
  stremio_data:
