version: "3.3"
services:
  server:
    container_name: stremio_server
    image: stremio/server:latest
    ports:
      - 11470:11470
      - 12470:12470
    volumes:
      - /usr/bin/ffmpeg:/usr/bin/ffmpeg:ro
      - /usr/bin/ffprobe:/usr/bin/ffprobe:ro
      - stremio_data:/root/.stremio-server
    networks:
      - proxy
    environment:
      - FFMPEG_BIN=/usr/bin/ffmpeg
      - FFPROBE_BIN=/usr/bin/ffprobe
      - APP_PATH=/root/.stremio-server
      - NO_CORS=1
      - CASTING_DISABLED=1

volumes:
  stremio_data:

networks:
  proxy:
    external: true
