version: "3.3"

services:
  stremio-server:
    image: stremio-server:custom
    container_name: stremio_server
    ports:
      - "11470:11470"
      - "12470:12470"
    volumes:
      - stremio_data:/root/.stremio-server
    environment:
      # Dockerfile'daki env'lere ek olarak istersek override edebiliriz:
      # - NO_CORS=1
      # - CASTING_DISABLED=1
    restart: unless-stopped

volumes:
  stremio_data:
